[project]
name = "streamlit-apps"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain>=0.3.21",
    "phidata>=2.7.10",
    "streamlit>=1.44.0",
]
